title: ggarlic's blog
author: ggarlic
name: ggarlic
email : yangbo.ggarlic@gmail.com
author_email: yangbo.ggarlic@gmail.com
encoding: utf-8
github_username: ggarlic
twitter_username: ggarlic
permalink: "/blog/:year/:month/:title"
description: cat ~ggarlic/life > /dev/null
paginate: 10

gems:
    - jekyll-feed
    - jekyll-paginate
highlighter: rouge
redcarpet:
  extensions:
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
